In [ ]:
#Installing SQL module in the notebook

In [1]:
!pip install ipython-sql

Collecting ipython-sql
  Downloading https://files.pythonhosted.org/packages/ab/df/427e7cf05ffc67e78672ad57dce2436c1e825129033effe6fcaf804d0c60/ipython_sql-0.3.9-py2.py3-none-any.whl
Collecting sqlparse (from ipython-sql)
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: sqlalchemy>=0.6.7 in ./anaconda3/lib/python3.7/site-packages (from ipython-sql) (1.3.1)
Requirement already satisfied: ipython-genutils>=0.1.0 in ./anaconda3/lib/python3.7/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from ipython-sql) (1.12.0)
Collecting prettytable (from ipython-sql)
  Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Requirement already satisfied: ipython>=1.0 in ./anaconda3/lib/python3.7/site-packages (from ipython-sql) (7.4.0)
Requirement already satisfied: setuptools>=18.5 in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (40.8.0)
Requirement already satisfied: traitlets>=4.2 in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.3.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.0.9)
Requirement already satisfied: backcall in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.6.0)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.3.1)
Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: jedi>=0.10 in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.13.3)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
Requirement already satisfied: decorator in ./anaconda3/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.4.0)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.7/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.1.7)
Requirement already satisfied: ptyprocess>=0.5 in ./anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)
Requirement already satisfied: parso>=0.3.0 in ./anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.3.4)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Stored in directory: /Users/youjia/Library/Caches/pip/wheels/80/34/1c/3967380d9676d162cb59513bd9dc862d0584e045a162095606
Successfully built prettytable
Installing collected packages: sqlparse, prettytable, ipython-sql
Successfully installed ipython-sql-0.3.9 prettytable-0.7.2 sqlparse-0.3.0

In [ ]:
#Loading the SQL module

In [3]:
%load_ext sql

In [ ]:
#connect to a SQLite database.
#‘Connected: @None' means the connection has been established.

In [4]:
%sql sqlite://

'Connected: @None'

In [ ]:
#create a demo table called EMPLOYEES to showcase the function.

In [4]:
%%sql
CREATE TABLE EMPLOYEE(firstname varchar(50),lastname varchar(50));  
INSERT INTO EMPLOYEE VALUES('Tom','Mitchell');  
INSERT INTO EMPLOYEE VALUES('Jack','Ryan');

 * sqlite://
Done.
1 rows affected.
1 rows affected.

[]

In [13]:
%sql SELECT * FROM EMPLOYEE;

 * sqlite://
Done.

[('Tom', 'Mitchell'), ('Jack', 'Ryan')]

In [ ]:
#making use of the SQL_SAFI database
#download from https://github.com/parulnith/SQL-Interface-within-JupyterLab/blob/master/SQL_SAFI.sqlite

In [17]:
#Specifying the path of the database  
%sql sqlite:////Users/youjia/SQL_SAFI.sqlite

'Connected: @/Users/youjia/SQL_SAFI.sqlite'

In [18]:
%sql select * from Crops

   sqlite://
 * sqlite:////Users/youjia/SQL_SAFI.sqlite
Done.

[(1, 1, 1, 1, 'maize', 1),
 (1, 2, 1, 1, 'maize', 1),
 (2, 1, 1, 1, 'maize', 1),
 (2, 2, 1, 1, 'tomatoes', 1),
 (2, 3, 1, 1, 'vegetable', 1),
 (3, 1, 1, 1, 'maize', 1),
 (4, 1, 1, 1, 'maize', 1),
 (4, 2, 1, 1, 'maize', 1),
 (4, 3, 1, 1, 'sorghum', 1),
 (5, 1, 1, 1, 'maize', 1),
 (5, 2, 1, 1, 'maize', 1),
 (6, 1, 1, 1, 'maize', 1),
 (7, 1, 1, 1, 'maize', 1),
 (7, 2, 1, 1, 'tomatoes', 1),
 (7, 3, 1, 1, 'beans', 1),
 (7, 4, 1, 1, 'vegetable', 1),
 (8, 1, 1, 1, 'maize', 1),
 (8, 2, 1, 1, 'maize', 1),
 (9, 1, 1, 1, 'maize', 1),
 (9, 2, 1, 1, 'tomatoes', 1),
 (9, 3, 1, 1, 'vegetable', 1),
 (10, 1, 1, 1, 'maize', 1),
 (10, 2, 1, 1, 'tomatoes', 1),
 (11, 1, 1, 1, 'maize', 1),
 (11, 2, 1, 1, 'maize', 1),
 (12, 1, 1, 0, 'maize', 0),
 (12, 2, 1, 1, 'tomatoes', 1),
 (13, 1, 1, 1, 'maize', 1),
 (13, 2, 1, 1, 'beans', 1),
 (13, 3, 1, 1, 'vegetable', 1),
 (13, 4, 1, 1, 'onion', 1),
 (14, 1, 1, 1, 'maize', 1),
 (14, 2, 1, 1, 'maize', 1),
 (14, 3, 1, 1, 'maize', 1),
 (15, 1, 1, 1, 'maize', 1),
 (15, 2, 1, 1, 'beans', 1),
 (15, 3, 1, 1, 'ngogwe', 1),
 (16, 1, 1, 1, 'maize', 1),
 (17, 1, 1, 1, 'maize', 1),
 (17, 2, 1, 1, 'vegetable', 1),
 (17, 3, 1, 1, 'other', 1),
 (18, 1, 1, 1, 'maize', 1),
 (18, 2, 1, 1, 'pigeonpeas', 1),
 (19, 1, 1, 1, 'maize', 1),
 (19, 2, 1, 1, 'beans', 1),
 (20, 1, 1, 1, 'maize', 1),
 (20, 2, 1, 1, 'beans', 1),
 (21, 1, 1, 1, 'maize', 1),
 (21, 2, 1, 1, 'vegetable', 1),
 (21, 3, 1, 1, 'tomatoes', 1),
 (21, 4, 1, 1, 'cabbage', 1),
 (22, 1, 1, 1, 'maize', 1),
 (23, 1, 1, 1, 'maize', 1),
 (23, 2, 1, 1, 'amendoim', 1),
 (24, 1, 1, 1, 'maize', 1),
 (24, 2, 1, 1, 'tomatoes', 1),
 (24, 3, 1, 1, 'peanut', 1),
 (25, 1, 1, 1, 'maize', 1),
 (25, 2, 1, 1, 'tomatoes', 1),
 (25, 3, 1, 1, 'cabbage', 1),
 (26, 1, 1, 1, 'maize', 1),
 (26, 2, 1, 1, 'beans', 1),
 (27, 1, 1, 1, 'maize', 1),
 (27, 2, 1, 1, 'beans', 1),
 (28, 1, 1, 1, 'maize', 1),
 (28, 2, 1, 1, 'tomatoes', 1),
 (28, 3, 1, 1, 'vegetable', 1),
 (29, 1, 1, 1, 'maize', 1),
 (29, 2, 1, 1, 'tomatoes', 1),
 (29, 3, 1, 1, 'beans', 1),
 (30, 1, 1, 1, 'maize', 1),
 (31, 1, 1, 1, 'maize', 1),
 (32, 1, 1, 1, 'maize', 1),
 (32, 2, 1, 1, 'sorghum', 1),
 (32, 3, 1, 1, 'sunflower', 1),
 (32, 4, 1, 1, 'peanut', 1),
 (32, 5, 1, 1, 'tomatoes', 1),
 (32, 6, 1, 1, 'onion', 1),
 (32, 7, 1, 1, 'cabbage', 1),
 (32, 8, 1, 1, 'vegetable', 1),
 (33, 1, 1, 1, 'maize', 1),
 (33, 2, 1, 1, 'tomatoes', 1),
 (34, 1, 1, 1, 'tomatoes', 1),
 (34, 2, 1, 1, 'maize', 1),
 (35, 1, 1, 1, 'tomatoes', 1),
 (35, 2, 1, 1, 'maize', 1),
 (36, 1, 1, 1, 'maize', 1),
 (36, 2, 1, 1, 'tomatoes', 1),
 (36, 3, 1, 1, 'vegetable', 1),
 (37, 1, 1, 1, 'maize', 1),
 (38, 1, 1, 1, 'maize', 1),
 (38, 2, 1, 1, 'tomatoes', 1),
 (39, 1, 1, 1, 'maize', 1),
 (40, 1, 1, 1, 'maize', 1),
 (40, 2, 1, 1, 'tomatoes', 1),
 (41, 1, 1, 1, 'maize', 1),
 (42, 1, 1, 1, 'maize', 1),
 (42, 2, 1, 1, 'other', 1),
 (43, 1, 1, 1, 'maize', 1),
 (43, 2, 1, 1, 'amendoim', 1),
 (43, 2, 2, 0, None, 0),
 (43, 3, 1, 1, 'vegetable', 1),
 (43, 4, 1, 1, 'tomatoes', 1),
 (43, 4, 2, 1, 'peanut', 1),
 (44, 1, 1, 1, 'maize', 1),
 (45, 1, 1, 1, 'maize', 1),
 (45, 2, 1, 1, 'tomatoes', 1),
 (45, 3, 1, 1, 'beans', 1),
 (46, 1, 1, 1, 'maize', 1),
 (46, 2, 1, 1, 'tomatoes', 1),
 (46, 3, 1, 1, 'vegetable', 1),
 (46, 4, 1, 1, 'onion', 1),
 (46, 5, 1, 1, 'beans', 1),
 (47, 1, 1, 1, 'maize', 1),
 (47, 2, 1, 1, 'tomatoes', 1),
 (48, 1, 1, 1, 'maize', 1),
 (48, 1, 2, 1, 'sorghum', 1),
 (49, 1, 1, 1, 'maize', 1),
 (49, 1, 2, 1, 'sorghum', 1),
 (50, 1, 1, 1, 'maize', 1),
 (50, 1, 2, 1, 'tomatoes', 1),
 (50, 1, 3, 1, 'piri_piri', 1),
 (51, 1, 1, 1, 'maize', 1),
 (52, 1, 1, 1, 'maize', 1),
 (53, 1, 1, 1, 'maize', 1),
 (53, 2, 1, 1, 'beans', 1),
 (53, 2, 2, 1, 'tomatoes', 1),
 (53, 2, 3, 1, 'cabbage', 1),
 (53, 2, 4, 1, 'vegetable', 1),
 (53, 3, 1, 1, 'maize', 1),
 (54, 1, 1, 1, 'maize', 1),
 (54, 1, 2, 1, 'tomatoes', 1),
 (55, 1, 1, 1, 'maize', 1),
 (56, 1, 1, 1, 'maize', 1),
 (56, 2, 1, 1, 'tomatoes', 1),
 (57, 1, 1, 1, 'maize', 1),
 (57, 2, 1, 1, 'other', 1),
 (58, 1, 1, 1, 'beans', 1),
 (58, 2, 1, 1, 'other', 1),
 (58, 3, 1, 1, 'maize', 1),
 (59, 1, 1, 1, 'maize', 1),
 (59, 1, 2, 1, 'other', 1),
 (59, 2, 1, 1, 'maize', 1),
 (60, 1, 1, 1, 'maize', 1),
 (60, 2, 1, 1, 'tomatoes', 1),
 (60, 3, 1, 1, 'peanut', 1),
 (61, 1, 1, 1, 'tomatoes', 1),
 (61, 1, 2, 1, 'onion', 1),
 (61, 1, 3, 1, 'cabbage', 1),
 (61, 1, 4, 1, 'vegetable', 1),
 (61, 1, 5, 1, 'piri_piri', 1),
 (61, 2, 1, 1, 'maize', 1),
 (62, 1, 1, 1, 'maize', 1),
 (62, 2, 1, 1, 'sorghum', 1),
 (63, 1, 1, 1, 'maize', 1),
 (63, 1, 2, 1, 'sesame', 1),
 (64, 1, 1, 1, 'maize', 1),
 (64, 2, 1, 1, 'sesame', 1),
 (65, 1, 1, 1, 'maize', 1),
 (65, 2, 1, 1, 'tomatoes', 1),
 (66, 1, 1, 1, 'beans', 1),
 (66, 1, 2, 1, 'tomatoes', 1),
 (66, 1, 3, 1, 'onion', 1),
 (66, 1, 4, 1, 'vegetable', 1),
 (67, 1, 1, 1, 'maize', 1),
 (67, 1, 2, 1, 'tomatoes', 1),
 (67, 1, 3, 1, 'vegetable', 1),
 (68, 1, 1, 1, 'maize', 1),
 (68, 2, 1, 1, 'piri_piri', 1),
 (68, 3, 1, 1, 'maize', 1),
 (69, 1, 1, 1, 'maize', 1),
 (69, 1, 2, 1, 'tomatoes', 1),
 (70, 1, 1, 1, 'maize', 1),
 (70, 1, 2, 1, None, 1),
 (70, 2, 1, 1, 'maize', 1),
 (70, 3, 1, 1, 'maize', 1),
 (71, 1, 1, 1, 'maize', 1),
 (71, 2, 1, 1, 'tomatoes', 1),
 (72, 1, 1, 1, 'maize', 1),
 (73, 1, 1, 1, 'maize', 1),
 (73, 1, 2, 1, 'vegetable', 1),
 (73, 1, 3, 1, 'peanut', 1),
 (74, 1, 1, 1, 'maize', 1),
 (74, 1, 2, 1, 'sorghum', 1),
 (74, 2, 1, 1, 'beans', 1),
 (74, 2, 2, 1, 'tomatoes', 1),
 (74, 2, 3, 1, 'vegetable', 1),
 (75, 1, 1, 1, 'maize', 1),
 (76, 1, 1, 1, 'maize', 1),
 (76, 2, 1, 1, 'other', 1),
 (77, 1, 1, 1, 'maize', 1),
 (77, 2, 1, 1, 'beans', 1),
 (77, 2, 2, 1, 'vegetable', 1),
 (77, 3, 1, 1, 'maize', 1),
 (78, 1, 1, 1, 'tomatoes', 1),
 (78, 1, 2, 1, 'onion', 1),
 (78, 1, 3, 1, 'vegetable', 1),
 (78, 2, 1, 1, 'maize', 1),
 (79, 1, 1, 1, 'maize', 1),
 (79, 1, 2, 1, 'sorghum', 1),
 (79, 2, 1, 1, 'tomatoes', 1),
 (80, 1, 1, 1, 'maize', 1),
 (80, 1, 2, 1, 'tomatoes', 1),
 (80, 1, 3, 1, 'vegetable', 1),
 (81, 1, 1, 1, 'maize', 1),
 (81, 1, 2, 1, 'beans', 1),
 (81, 1, 3, 1, 'bananas', 1),
 (81, 1, 4, 1, 'tomatoes', 1),
 (81, 1, 5, 1, 'vegetable', 1),
 (82, 1, 1, 1, 'maize', 1),
 (82, 1, 2, 1, 'beans', 1),
 (82, 1, 3, 1, 'tomatoes', 1),
 (82, 1, 4, 1, 'vegetable', 1),
 (83, 1, 1, 1, 'beans', 1),
 (83, 1, 2, 1, 'tomatoes', 1),
 (83, 1, 3, 1, 'vegetable', 1),
 (83, 2, 1, 1, 'maize', 1),
 (84, 1, 1, 1, 'maize', 1),
 (84, 2, 1, 1, 'tomatoes', 1),
 (84, 3, 1, 1, 'beans', 1),
 (85, 1, 1, 1, 'maize', 1),
 (85, 2, 1, 1, 'tomatoes', 1),
 (85, 2, 2, 1, 'vegetable', 1),
 (86, 1, 1, 1, 'maize', 1),
 (86, 2, 1, 1, 'beans', 1),
 (86, 2, 2, 1, 'tomatoes', 1),
 (86, 2, 3, 1, 'vegetable', 1),
 (87, 1, 1, 1, 'maize', 1),
 (87, 2, 1, 1, 'other', 1),
 (88, 1, 1, 1, 'maize', 1),
 (88, 2, 1, 1, 'maize', 1),
 (89, 1, 1, 1, 'maize', 1),
 (89, 2, 1, 1, 'tomatoes', 1),
 (90, 1, 1, 1, 'maize', 1),
 (90, 2, 1, 1, 'maize', 1),
 (90, 3, 1, 1, 'tomatoes', 1),
 (91, 1, 1, 1, 'tomatoes', 1),
 (91, 2, 1, 1, 'maize', 1),
 (91, 3, 1, 1, 'beans', 1),
 (92, 1, 1, 1, 'maize', 1),
 (92, 2, 1, 1, 'sorghum', 1),
 (92, 3, 1, 1, 'peanut', 1),
 (92, 4, 1, 1, 'cabbage', 1),
 (92, 5, 1, 1, 'tomatoes', 1),
 (92, 6, 1, 1, 'vegetable', 1),
 (93, 1, 1, 1, 'maize', 1),
 (93, 2, 1, 1, 'maize', 1),
 (93, 2, 2, 1, 'other', 1),
 (94, 1, 1, 1, 'maize', 1),
 (94, 2, 1, 1, 'beans', 1),
 (94, 2, 2, 1, None, 1),
 (94, 3, 1, 1, 'tomatoes', 1),
 (95, 1, 1, 1, 'maize', 1),
 (95, 2, 1, 1, 'maize', 1),
 (95, 2, 2, 1, 'beans', 1),
 (95, 2, 3, 1, 'vegetable', 1),
 (95, 2, 4, 1, 'other', 1),
 (96, 1, 1, 1, 'maize', 1),
 (96, 2, 1, 1, 'beans', 1),
 (96, 2, 2, 1, 'tomatoes', 1),
 (97, 1, 1, 1, 'maize', 1),
 (97, 1, 2, 1, 'sorghum', 1),
 (97, 2, 1, 1, 'beans', 1),
 (97, 2, 2, 1, 'bananas', 1),
 (97, 2, 3, 1, 'vegetable', 1),
 (97, 2, 4, 1, 'other', 1),
 (98, 1, 1, 1, 'maize', 1),
 (98, 2, 1, 1, 'tomatoes', 1),
 (98, 2, 2, 1, 'onion', 1),
 (99, 1, 1, 1, 'maize', 1),
 (99, 2, 1, 1, 'maize', 1),
 (99, 2, 2, 1, 'beans', 1),
 (99, 2, 3, 1, 'tomatoes', 1),
 (99, 2, 4, 1, 'onion', 1),
 (100, 1, 1, 1, 'maize', 1),
 (100, 1, 2, 1, 'sorghum', 1),
 (100, 1, 3, 1, 'tomatoes', 1),
 (100, 1, 4, 1, 'onion', 1),
 (100, 1, 5, 1, 'vegetable', 1),
 (101, 1, 1, 1, 'maize', 1),
 (101, 1, 2, 1, 'sorghum', 1),
 (101, 2, 1, 1, 'beans', 1),
 (101, 2, 2, 1, 'tomatoes', 1),
 (101, 3, 1, 1, 'beans', 1),
 (101, 3, 2, 1, 'tomatoes', 1),
 (101, 3, 3, 1, 'vegetable', 1),
 (101, 4, 1, 1, 'tomatoes', 1),
 (101, 4, 2, 2, 'baby_corn', 2),
 (102, 1, 1, 1, 'maize', 1),
 (102, 2, 1, 1, 'tomatoes', 1),
 (102, 2, 2, 1, 'vegetable', 1),
 (103, 1, 1, 1, 'baby_corn', 1),
 (103, 2, 1, 1, 'piri_piri', 1),
 (103, 3, 1, 1, 'maize', 1),
 (103, 4, 1, 1, 'cabbage', 1),
 (103, 5, 1, 1, 'tomatoes', 1),
 (104, 1, 1, 1, 'maize', 1),
 (104, 2, 1, 1, 'pigeonpeas', 1),
 (104, 3, 1, 1, 'sorghum', 1),
 (105, 1, 1, 1, 'maize', 1),
 (105, 2, 1, 1, 'maize', 1),
 (105, 3, 1, 1, 'maize', 1),
 (106, 1, 1, 1, 'maize', 1),
 (106, 2, 1, 1, 'beans', 1),
 (106, 2, 2, 1, 'onion', 1),
 (106, 3, 1, 1, 'other', 1),
 (107, 1, 1, 1, 'maize', 1),
 (108, 1, 1, 1, 'maize', 1),
 (108, 2, 1, 1, 'beans', 1),
 (108, 3, 1, 1, 'tomatoes', 1),
 (108, 3, 2, 1, 'onion', 1),
 (108, 3, 3, 1, 'vegetable', 1),
 (108, 3, 4, 1, 'cucumber', 1),
 (109, 1, 1, 1, 'maize', 1),
 (109, 1, 2, 1, 'potatoes', 1),
 (109, 2, 1, 1, 'maize', 1),
 (110, 1, 1, 1, 'maize', 1),
 (110, 2, 1, 1, 'maize', 1),
 (111, 1, 1, 1, 'maize', 1),
 (111, 1, 2, 1, 'sorghum', 1),
 (111, 2, 1, 1, 'maize', 1),
 (111, 3, 1, 1, 'vegetable', 1),
 (112, 1, 1, 1, 'maize', 1),
 (113, 1, 1, 1, 'maize', 1),
 (114, 1, 1, 1, 'maize', 1),
 (114, 2, 1, 1, 'tomatoes', 1),
 (115, 1, 1, 1, 'maize', 1),
 (115, 2, 1, 1, 'maize', 1),
 (115, 3, 1, 1, 'beans', 1),
 (115, 3, 2, 1, 'tomatoes', 1),
 (115, 3, 3, 1, 'piri_piri', 1),
 (116, 1, 1, 1, 'maize', 1),
 (116, 2, 1, 1, 'other', 1),
 (117, 1, 1, 1, 'maize', 1),
 (117, 2, 1, 1, 'sorghum', 1),
 (118, 1, 1, 1, 'maize', 1),
 (118, 2, 1, 1, 'beans', 1),
 (118, 3, 1, 1, 'tomatoes', 1),
 (119, 1, 1, 1, 'maize', 1),
 (119, 2, 1, 1, 'beans', 1),
 (120, 1, 1, 1, 'tomatoes', 1),
 (120, 2, 1, 1, 'maize', 1),
 (120, 3, 1, 1, 'maize', 1),
 (121, 1, 1, 1, 'maize', 1),
 (121, 2, 1, 1, 'tomatoes', 1),
 (122, 1, 1, 1, 'maize', 1),
 (122, 2, 1, 1, 'tomatoes', 1),
 (122, 3, 1, 1, 'tomatoes', 1),
 (123, 1, 1, 1, 'maize', 1),
 (123, 2, 1, 1, 'tomatoes', 1),
 (123, 2, 2, 1, 'vegetable', 1),
 (124, 1, 1, 1, 'maize', 1),
 (124, 2, 1, 1, 'piri_piri', 1),
 (124, 3, 1, 1, 'baby_corn', 1),
 (125, 1, 1, 1, 'tomatoes', 1),
 (125, 2, 1, 1, 'maize', 1),
 (126, 1, 1, 1, 'tomatoes', 1),
 (126, 2, 1, 1, 'maize', 1),
 (126, 3, 1, 1, 'baby_corn', 1),
 (127, 1, 1, 1, 'maize', 1),
 (127, 1, 2, 1, 'beans', 1),
 (127, 1, 3, 1, 'peanut', 1),
 (127, 2, 1, 1, 'tomatoes', 1),
 (128, 1, 1, 1, 'maize', 1),
 (128, 2, 1, 1, 'tomatoes', 1),
 (128, 3, 1, 1, 'cabbage', 1),
 (128, 4, 1, 1, 'maize', 1),
 (129, 1, 1, 1, 'maize', 1),
 (129, 2, 1, 1, 'tomatoes', 1),
 (130, 1, 1, 1, 'maize', 1),
 (130, 2, 1, 1, 'vegetable', 1),
 (131, 1, 1, 1, 'maize', 1),
 (131, 2, 1, 1, 'maize', 1),
 (132, 1, 1, 1, 'peanut', 1),
 (132, 1, 2, 1, 'manioc', 1),
 (132, 2, 1, 1, 'beans', 1),
 (133, 1, 1, 1, 'maize', 1),
 (133, 2, 1, 1, 'pigeonpeas', 1),
 (133, 3, 1, 1, 'manioc', 1),
 (133, 3, 2, 0, None, 0),
 (134, 1, 1, 1, 'maize', 1),
 (134, 2, 1, 1, 'rice', 1),
 (134, 3, 1, 1, 'sorghum', 1),
 (134, 4, 1, 1, 'tomatoes', 1),
 (134, 4, 2, 1, 'onion', 1),
 (134, 4, 3, 1, 'green_pepper', 1),
 (135, 1, 1, 1, 'maize', 1),
 (135, 2, 1, 1, 'maize', 1),
 (135, 2, 2, 1, 'sorghum', 1),
 (135, 3, 1, 1, 'vegetable', 1),
 (136, 1, 1, 1, 'rice', 1),
 (136, 2, 1, 1, 'maize', 1),
 (136, 3, 1, 1, 'sorghum', 1),
 (137, 1, 1, 1, 'maize', 1),
 (137, 1, 2, 1, 'sorghum', 1),
 (137, 2, 1, 1, 'rice', 1),
 (138, 1, 1, 1, 'maize', 1),
 (138, 2, 1, 1, 'sorghum', 1),
 (138, 3, 1, 1, 'tomatoes', 1),
 (139, 1, 1, 1, 'maize', 1),
 (139, 1, 2, 1, 'beans', 1),
 (139, 1, 3, 1, 'sweetpotato', 1),
 (139, 1, 4, 1, 'ngogwe', 1),
 (139, 1, 5, 1, 'vegetable', 1),
 (140, 1, 1, 1, 'maize', 1),
 (140, 2, 1, 1, 'sorghum', 1),
 (140, 3, 1, 1, 'tomatoes', 1),
 (140, 3, 2, 1, 'vegetable', 1),
 (140, 3, 3, 1, 'piri_piri', 1),
 (141, 1, 1, 1, 'rice', 1),
 (141, 2, 1, 1, 'maize', 1),
 (141, 3, 1, 1, 'onion', 1),
 (141, 3, 2, 1, 'vegetable', 1),
 (142, 1, 1, 1, 'rice', 1),
 (142, 2, 1, 1, 'maize', 1),
 (142, 3, 1, 1, 'onion', 1),
 (142, 3, 2, 1, 'vegetable', 1),
 (142, 4, 1, 1, 'beans', 1),
 (142, 5, 1, 1, 'sesame', 1),
 (143, 1, 1, 1, 'maize', 1),
 (143, 2, 1, 1, 'rice', 1),
 (144, 1, 1, 1, 'maize', 1),
 (144, 1, 2, 1, 'sorghum', 1),
 (144, 2, 1, 1, 'tomatoes', 1),
 (145, 1, 1, 1, 'maize', 1),
 (145, 2, 1, 1, 'maize', 1),
 (145, 2, 2, 1, 'sorghum', 1),
 (146, 1, 1, 1, 'maize', 1),
 (146, 1, 2, 1, 'sesame', 1),
 (146, 1, 3, 1, 'piri_piri', 1),
 (146, 2, 1, 1, 'rice', 1),
 (146, 3, 1, 1, 'sorghum', 1),
 (147, 1, 1, 1, 'maize', 1),
 (147, 2, 1, 1, 'rice', 1),
 (147, 3, 1, 1, 'sorghum', 1),
 (148, 1, 1, 1, 'maize', 1),
 (148, 1, 2, 1, 'sorghum', 1),
 (148, 2, 1, 1, 'rice', 1),
 (149, 1, 1, 1, 'maize', 1),
 (149, 2, 1, 1, 'maize', 1),
 (149, 3, 1, 1, 'sorghum', 1),
 (149, 4, 1, 1, 'sorghum', 1),
 (150, 1, 1, 1, 'maize', 1),
 (150, 2, 1, 1, 'tomatoes', 1),
 (150, 2, 2, 1, 'vegetable', 1),
 (151, 1, 1, 1, 'maize', 1),
 (151, 2, 1, 1, 'sorghum', 1),
 (151, 3, 1, 1, 'rice', 1),
 (152, 1, 1, 1, 'maize', 1),
 (152, 2, 1, 1, 'rice', 1),
 (152, 3, 1, 1, 'tomatoes', 1),
 (152, 3, 2, 1, 'onion', 1),
 (152, 3, 3, 1, 'vegetable', 1),
 (152, 4, 1, 1, 'sorghum', 1),
 (153, 1, 1, 1, 'maize', 1),
 (153, 2, 1, 1, 'sorghum', 1),
 (153, 3, 1, 1, 'rice', 1),
 (154, 1, 1, 1, 'maize', 1),
 (154, 2, 1, 1, 'sorghum', 1),
 (154, 3, 1, 1, 'sorghum', 1),
 (155, 1, 1, 1, 'maize', 1),
 (155, 2, 1, 1, 'maize', 1),
 (156, 1, 1, 1, 'maize', 1),
 (156, 2, 1, 1, 'rice', 1),
 (156, 3, 1, 1, 'tomatoes', 1),
 (157, 1, 1, 1, 'sesame', 1),
 (157, 2, 1, 1, 'maize', 1),
 (157, 3, 1, 1, 'sorghum', 1),
 (157, 4, 1, 1, 'tomatoes', 1),
 (157, 4, 2, 1, 'vegetable', 1),
 (158, 1, 1, 1, 'maize', 1),
 (158, 2, 1, 1, 'rice', 1),
 (159, 1, 1, 1, 'maize', 1),
 (159, 1, 2, 1, 'sorghum', 1),
 (159, 1, 3, 1, 'cassava', 1),
 (160, 1, 1, 1, 'sorghum', 1),
 (160, 1, 2, 1, 'rice', 1),
 (161, 1, 1, 1, 'rice', 1),
 (161, 2, 1, 1, 'sorghum', 1),
 (162, 1, 1, 1, 'maize', 1),
 (162, 1, 2, 1, 'sorghum', 1),
 (162, 2, 1, 1, 'rice', 1),
 (163, 1, 1, 1, 'sorghum', 1),
 (163, 2, 1, 1, 'rice', 1),
 (164, 1, 1, 1, 'maize', 1),
 (164, 1, 2, 1, 'sorghum', 1),
 (164, 1, 3, 1, 'rice', 1),
 (165, 1, 1, 1, 'maize', 1),
 (165, 1, 2, 1, 'beans', 1),
 (165, 1, 3, 1, 'sorghum', 1),
 (165, 1, 4, 1, 'cassava', 1),
 (165, 2, 1, 1, 'rice', 1),
 (166, 1, 1, 1, 'maize', 1),
 (166, 1, 2, 1, 'sorghum', 1),
 (166, 2, 1, 1, 'rice', 1),
 (167, 1, 1, 1, 'maize', 1),
 (167, 1, 2, 1, 'sorghum', 1),
 (167, 1, 3, 1, 'rice', 1),
 (168, 1, 1, 1, 'maize', 1),
 (168, 1, 2, 1, 'beans', 1),
 (168, 1, 3, 1, 'sorghum', 1),
 (168, 1, 4, 1, 'cassava', 1),
 (168, 1, 5, 1, 'peanut', 1),
 (168, 2, 1, 1, 'rice', 1),
 (169, 1, 1, 1, 'maize', 1),
 (169, 1, 2, 1, 'sorghum', 1),
 (169, 1, 3, 1, 'rice', 1),
 (170, 1, 1, 1, 'maize', 1),
 (170, 2, 1, 1, 'sorghum', 1),
 (170, 3, 1, 1, 'rice', 1),
 (171, 1, 1, 1, 'maize', 1),
 (171, 1, 2, 1, 'sorghum', 1),
 (171, 2, 1, 1, 'maize', 1),
 (171, 2, 2, 1, 'tomatoes', 1),
 (172, 1, 1, 1, 'maize', 1),
 (172, 1, 2, 1, 'sorghum', 1),
 (172, 2, 1, 1, 'onion', 1),
 (172, 2, 2, 1, 'vegetable', 1),
 (172, 3, 1, 1, 'maize', 1),
 (172, 3, 2, 1, 'sorghum', 1),
 (172, 3, 3, 1, 'tomatoes', 1),
 (172, 3, 4, 1, 'sesame', 1),
 (173, 1, 1, 1, 'maize', 1),
 (173, 2, 1, 1, 'rice', 1),
 (173, 2, 2, 1, 'vegetable', 1),
 (174, 1, 1, 1, 'maize', 1),
 (174, 1, 2, 1, 'sorghum', 1),
 (174, 2, 1, 1, 'maize', 1),
 (174, 2, 2, 1, 'rice', 1),
 (175, 1, 1, 1, 'rice', 1),
 (175, 2, 1, 1, 'rice', 1),
 (175, 3, 1, 1, 'maize', 1),
 (175, 3, 2, 1, 'sorghum', 1),
 (176, 1, 1, 1, 'rice', 1),
 (176, 2, 1, 1, 'rice', 1),
 (176, 3, 1, 1, 'maize', 1),
 (176, 3, 2, 1, 'sorghum', 1),
 (177, 1, 1, 1, 'rice', 1),
 (177, 2, 1, 1, 'maize', 1),
 (177, 2, 2, 1, 'sesame', 1),
 (178, 1, 1, 1, 'maize', 1),
 (178, 2, 1, 1, 'maize', 1),
 (178, 3, 1, 1, 'rice', 1),
 (179, 1, 1, 1, 'maize', 1),
 (179, 1, 2, 1, 'sorghum', 1),
 (179, 2, 1, 1, 'rice', 1),
 (180, 1, 1, 1, 'maize', 1),
 (180, 2, 1, 1, 'rice', 1),
 (181, 1, 1, 1, 'maize', 1),
 (181, 2, 1, 1, 'maize', 1),
 (181, 3, 1, 1, 'rice', 1),
 (182, 1, 1, 1, 'maize', 1),
 (182, 2, 1, 1, 'rice', 1),
 (183, 1, 1, 1, 'rice', 1),
 (183, 2, 1, 1, 'maize', 1),
 (184, 1, 1, 1, 'pigeonpeas', 1),
 (184, 1, 2, 1, 'maize', 1),
 (184, 1, 3, 1, 'sesame', 1),
 (184, 2, 1, 1, 'other', 1),
 (185, 1, 1, 1, 'maize', 1),
 (185, 2, 1, 1, 'sorghum', 1),
 (185, 3, 1, 1, 'rice', 1),
 (186, 1, 1, 1, 'maize', 1),
 (186, 1, 2, 1, 'sorghum', 1),
 (186, 2, 1, 1, 'rice', 1),
 (187, 1, 1, 1, 'maize', 1),
 (187, 1, 2, 1, 'sorghum', 1),
 (187, 2, 1, 1, 'rice', 1),
 (188, 1, 1, 1, 'maize', 1),
 (188, 1, 2, 1, 'sorghum', 1),
 (189, 1, 1, 1, 'sorghum', 1),
 (189, 2, 1, 1, 'maize', 1),
 (189, 3, 1, 1, 'rice', 1),
 (189, 4, 1, 1, 'tomatoes', 1),
 (190, 1, 1, 1, 'maize', 1),
 (190, 1, 2, 1, 'sorghum', 1),
 (190, 2, 1, 1, 'rice', 1),
 (191, 1, 1, 1, 'maize', 1),
 (191, 2, 1, 1, 'sorghum', 1),
 (191, 3, 1, 1, 'rice', 1),
 (192, 1, 1, 1, 'maize', 1),
 (192, 1, 2, 1, 'sorghum', 1),
 (192, 2, 1, 1, 'maize', 1),
 (192, 3, 1, 1, 'other', 1),
 (193, 1, 1, 1, 'maize', 1),
 (193, 1, 2, 1, 'sorghum', 1),
 (193, 2, 1, 1, 'pigeonpeas', 1),
 (193, 2, 2, 1, 'maize', 1),
 (193, 2, 3, 1, 'sorghum', 1),
 (194, 1, 1, 1, 'maize', 1),
 (194, 2, 1, 1, 'other', 1),
 (195, 1, 1, 1, 'sorghum', 1),
 (195, 2, 1, 1, 'rice', 1),
 (195, 3, 1, 1, 'maize', 1),
 (196, 1, 1, 1, 'sorghum', 1),
 (196, 2, 1, 1, 'maize', 1),
 (196, 3, 1, 1, 'rice', 1),
 (197, 1, 1, 1, 'maize', 1),
 (197, 2, 1, 1, 'sorghum', 1),
 (197, 3, 1, 1, 'rice', 1),
 (197, 4, 1, 1, 'millet', 1),
 (198, 1, 1, 1, 'maize', 1),
 (198, 1, 2, 1, 'sorghum', 1),
 (198, 2, 1, 1, 'rice', 1),
 (199, 1, 1, 1, 'maize', 1),
 (199, 1, 2, 1, 'sorghum', 1),
 (199, 1, 3, 1, 'millet', 1),
 (199, 2, 1, 1, 'other', 1),
 (199, 3, 1, 1, 'maize', 1),
 (199, 4, 1, 1, 'maize', 1),
 (200, 1, 1, 1, 'maize', 1),
 (200, 2, 1, 1, 'sorghum', 1),
 (200, 3, 1, 1, 'rice', 1),
 (201, 1, 1, 1, 'other', 1),
 (201, 2, 1, 1, 'maize', 1),
 (201, 2, 2, 1, 'sorghum', 1),
 (201, 2, 3, 1, 'sesame', 1),
 (202, 1, 1, 1, 'maize', 1),
 (202, 1, 2, 1, 'sorghum', 1),
 (202, 2, 1, 1, 'rice', 1),
 (203, 1, 1, 1, 'rice', 1),
 (203, 2, 1, 1, 'maize', 1),
 (203, 2, 2, 1, 'sorghum', 1),
 (204, 1, 1, 1, 'maize', 1),
 (204, 2, 1, 1, 'rice', 1),
 (205, 1, 1, 1, 'maize', 1),
 (205, 2, 1, 1, 'sorghum', 1),
 (205, 3, 1, 1, 'sweetpotato', 1),
 (205, 4, 1, 1, 'rice', 1),
 (206, 1, 1, 1, 'maize', 1),
 (206, 1, 2, 1, 'sorghum', 1),
 (206, 2, 1, 1, 'rice', 1),
 (207, 1, 1, 1, 'maize', 1),
 (207, 2, 1, 1, 'rice', 1),
 (208, 1, 1, 1, 'maize', 1),
 (208, 1, 2, 1, 'sorghum', 1),
 (209, 1, 1, 1, 'rice', 1),
 (209, 2, 1, 1, 'maize', 1),
 (210, 1, 1, 1, 'maize', 1),
 (210, 1, 2, 1, 'sorghum', 1),
 (210, 2, 1, 1, 'tomatoes', 1),
 (211, 1, 1, 1, 'maize', 1),
 (211, 2, 1, 1, 'rice', 1),
 (212, 1, 1, 1, 'maize', 1),
 (212, 2, 1, 1, 'sorghum', 1),
 (212, 3, 1, 1, 'other', 1),
 (213, 1, 1, 1, 'rice', 1),
 (213, 2, 1, 1, 'maize', 1),
 (214, 1, 1, 1, 'maize', 1),
 (214, 1, 2, 1, 'sorghum', 1),
 (214, 2, 1, 1, 'rice', 1),
 (215, 1, 1, 1, 'sesame', 1),
 (215, 2, 1, 1, 'maize', 1),
 (216, 1, 1, 1, 'maize', 1),
 (216, 1, 2, 1, 'sorghum', 1),
 (216, 2, 1, 1, 'rice', 1),
 (217, 1, 1, 1, 'sorghum', 1),
 (217, 2, 1, 1, 'maize', 1),
 (218, 1, 1, 1, 'maize', 1),
 (218, 2, 1, 1, 'rice', 1),
 (219, 1, 1, 1, 'maize', 1),
 (219, 1, 2, 1, 'sesame', 1),
 (219, 2, 1, 1, 'rice', 1),
 (220, 1, 1, 1, 'maize', 1),
 (220, 1, 2, 1, 'sorghum', 1),
 (220, 2, 1, 1, 'rice', 1),
 (221, 1, 1, 1, 'maize', 1),
 (221, 2, 1, 1, 'rice', 1),
 (222, 1, 1, 1, 'other', 1),
 (222, 2, 1, 1, 'maize', 1),
 (222, 2, 2, 1, 'sorghum', 1),
 (222, 3, 1, 1, 'rice', 1),
 (223, 1, 1, 1, 'maize', 1),
 (223, 2, 1, 1, 'maize', 1),
 (223, 2, 2, 1, 'sorghum', 1),
 (224, 1, 1, 1, 'maize', 1),

In [19]:
%sql select * from Crops where D_curr_crop = "maize" AND ID <=3;

   sqlite://
 * sqlite:////Users/youjia/SQL_SAFI.sqlite
Done.

[(1, 1, 1, 1, 'maize', 1),
 (1, 2, 1, 1, 'maize', 1),
 (2, 1, 1, 1, 'maize', 1),
 (3, 1, 1, 1, 'maize', 1)]

In [21]:
#The result can also be converted to a pandas dataframe
result = %sql select * from Crops where D_curr_crop = "maize" AND ID <=3;
dataframe = result.DataFrame()
dataframe.info()

   sqlite://
 * sqlite:////Users/youjia/SQL_SAFI.sqlite
Done.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
Id                      4 non-null int64
plot_Id                 4 non-null int64
crop_Id                 4 non-null int64
D05_times               4 non-null int64
D_curr_crop             4 non-null object
D_repeat_times_count    4 non-null int64
dtypes: int64(5), object(1)
memory usage: 272.0+ bytes

In [23]:
#how to install JupyterLab extensions
#To install JupyterLab extensions, you need to have Node.js install.
#run the following commands in the given order
#1
#brew install node #for MacOS users
#or
#conda install -c conda-forge nodejs  
#pip install jupyterlab_sql
#jupyter serverextension enable jupyterlab_sql --py --sys-prefix
#jupyter lab build

In [ ]:
#attention
#To install jupyterlab-sql on versions of JupyterLab pre 1.0, run as follows:

# pip install jupyterlab_sql==0.2.1
# jupyter serverextension enable jupyterlab_sql --py --sys-prefix
# jupyter lab build

In [ ]:
#launch SQL in jupyterlab
#please refer to this URL https://www.datacamp.com/community/tutorials/sql-interface-within-jupyterlab

In [4]:
%sql sqlite://

'Connected: @None'

In [5]:
%sql mysql://

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite://'])
No module named 'MySQLdb'
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys(['sqlite://'])

In [11]:
!pip install pymysql

Collecting pymysql
  Downloading https://files.pythonhosted.org/packages/ed/39/15045ae46f2a123019aa968dfcba0396c161c20f855f11dea6796bcaae95/PyMySQL-0.9.3-py2.py3-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 2.0MB/s
Installing collected packages: pymysql
Successfully installed pymysql-0.9.3

In [17]:
!pip install mysql-connector

Collecting mysql-connector
  Downloading https://files.pythonhosted.org/packages/28/04/e40098f3730e75bbe36a338926f566ea803550a34fb50535499f4fc4787a/mysql-connector-2.2.9.tar.gz (11.9MB)
    100% |████████████████████████████████| 11.9MB 407kB/s
Building wheels for collected packages: mysql-connector
  Building wheel for mysql-connector (setup.py) ... done
  Stored in directory: /Users/youjia/Library/Caches/pip/wheels/8c/83/a1/f8b6d4bb1bd6208bbde1608bbfa7557504bed9eaf2ecf8c175
Successfully built mysql-connector
Installing collected packages: mysql-connector
Successfully installed mysql-connector-2.2.9

In [18]:
import mysql.connector

In [1]:
import pymysql

connection = pymysql.connect(host='localhost',
                             port=3306,
                             user='youjia',
                             password='zhanglijuan1012',
                             db='mydb',
                             charset='utf8')

OperationalError: (1045, "Access denied for user 'youjia'@'localhost' (using password: YES)")

In [2]:
import pymysql
def connectdb():
    print('连接到mysql服务器...')
    db = pymysql.connect(
        host="localhost",
        user="root",
        passwd="",
        port=3306,
        db="mydb",
        charset='utf8',
        cursorclass=pymysql.cursors.DictCursor)
    print('连接上了!')
    return db

In [3]:
connectdb()

连接到mysql服务器...
连接上了!

In [11]:
import pymysql

connection = pymysql.connect(host='localhost',
                             port=3306,
                             user='root',
                             password='',
                             db='mydb',
                             charset='utf8')
# 使用cursor()方法获取操作游标 
cursor = connection.cursor()
 
# SQL 查询语句
sql = "SELECT * from disney"
try:
   # 执行SQL语句
   cursor.execute(sql)
   # 获取所有记录列表
   results = cursor.fetchall()
   for row in results:
    print(row)
except:
    print ("Error: unable to fetch data")
connection.close()

(2011, 31.0, 69.0, 18.6, 51.2, 11.9, 18.3, 70.2, 11.2, 6.8, 4.1, 6.4, 1.3)
(2012, 31.0, 69.0, 19.9, 49.6, 12.6, 17.9, 67.5, 11.1, 7.3, 4.2, 7.3, 2.6)
(2013, 29.8, 70.2, 21.1, 49.5, 12.7, 16.7, 64.6, 11.6, 7.6, 4.0, 8.3, 3.9)
(2014, 30.0, 70.0, 20.4, 49.5, 13.5, 16.6, 66.2, 11.0, 7.0, 3.8, 7.0, 5.0)
(2015, 29.5, 70.5, 20.7, 49.6, 13.7, 16.0, 66.7, 10.8, 6.3, 3.4, 6.8, 6.0)
(2016, 29.7, 70.3, 20.7, 50.1, 13.6, 15.6, 64.7, 10.1, 6.6, 3.2, 6.9, 8.5)
(2017, 30.4, 69.6, 20.1, 50.9, 13.5, 15.5, 63.6, 10.1, 6.5, 3.3, 6.7, 9.8)
(2018, 27.7, 72.3, 21.2, 50.7, 12.9, 15.2, 60.8, 10.8, 7.5, 3.4, 7.9, 9.6)